development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: cable_tutorial_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://10.10.3.153:6381
  channel_prefix: appname_production